/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedYouthHubRouteImport } from './routes/_authenticated/youth-hub'
import { Route as AuthenticatedCampaignAdminRouteImport } from './routes/_authenticated/campaign-admin'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedYouthHubRoute = AuthenticatedYouthHubRouteImport.update({
  id: '/youth-hub',
  path: '/youth-hub',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCampaignAdminRoute =
  AuthenticatedCampaignAdminRouteImport.update({
    id: '/campaign-admin',
    path: '/campaign-admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/campaign-admin': typeof AuthenticatedCampaignAdminRoute
  '/youth-hub': typeof AuthenticatedYouthHubRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/campaign-admin': typeof AuthenticatedCampaignAdminRoute
  '/youth-hub': typeof AuthenticatedYouthHubRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/campaign-admin': typeof AuthenticatedCampaignAdminRoute
  '/_authenticated/youth-hub': typeof AuthenticatedYouthHubRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/campaign-admin' | '/youth-hub'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/campaign-admin' | '/youth-hub'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/campaign-admin'
    | '/_authenticated/youth-hub'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/youth-hub': {
      id: '/_authenticated/youth-hub'
      path: '/youth-hub'
      fullPath: '/youth-hub'
      preLoaderRoute: typeof AuthenticatedYouthHubRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaign-admin': {
      id: '/_authenticated/campaign-admin'
      path: '/campaign-admin'
      fullPath: '/campaign-admin'
      preLoaderRoute: typeof AuthenticatedCampaignAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCampaignAdminRoute: typeof AuthenticatedCampaignAdminRoute
  AuthenticatedYouthHubRoute: typeof AuthenticatedYouthHubRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCampaignAdminRoute: AuthenticatedCampaignAdminRoute,
  AuthenticatedYouthHubRoute: AuthenticatedYouthHubRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
